FROM wazuh/wazuh-dashboard:4.11.0
COPY ./config/wazuh_dashboard/opensearch_dashboards.yml /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
COPY ./config/wazuh_dashboard/wazuh.yml   /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
